/**
 * Cut the grass autotile banks, dark-grass edges, and dirt cliff into runtime pixels.
 * Source sheet stays in the gitignored pack. Re-run only when that sheet changes.
 *
 *   npx vite-node scripts/cut-shores.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { readPng, type Rgba } from './png';
import { CACHE, packRoot } from './pack-paths';

const PACK = packRoot();
const TILE = 16;
const OUT = path.join(CACHE, 'tiles/shores.ts');

function crop(sheet: Rgba, col: number, row: number): Int32Array {
  const px = new Int32Array(TILE * TILE);
  for (let y = 0; y < TILE; y += 1) {
    for (let x = 0; x < TILE; x += 1) {
      const o = ((row * TILE + y) * sheet.width + col * TILE + x) * 4;
      const a = sheet.data[o + 3]!;
      const r = sheet.data[o]!;
      const g = sheet.data[o + 1]!;
      const b = sheet.data[o + 2]!;
      const hole = a < 16 || (r < 16 && g < 16 && b < 16);
      px[y * TILE + x] = hole ? -1 : (r << 16) | (g << 8) | b;
    }
  }
  return px;
}

function hexOf(px: Int32Array): string {
  let s = '';
  for (let i = 0; i < px.length; i += 1) {
    const c = px[i]!;
    s += c < 0 ? '000000' : (c & 0xffffff).toString(16).padStart(6, '0');
  }
  return s;
}

/** Rows 0–3 of the grass sheet: cols 0–11 light over a hole, cols 12–23 the same shapes in dark. */
const grass = readPng(path.join(PACK, 'Tileset/Tileset Grass Summer.png'));
function block(originCol: number): Int32Array[] {
  const out: Int32Array[] = [];
  for (let row = 0; row < 4; row += 1) {
    for (let col = originCol; col < originCol + 12; col += 1) out.push(crop(grass, col, row));
  }
  return out;
}
const tiles = block(0);
const darkEdges = block(12);

/** Dirt face, cols 0–11. Cols 12–16 are the dark arches, which read as caves. */
const cliff = readPng(path.join(PACK, 'Tileset/Tileset Grass Cliff Tileset Summer.png'));
const cliffCap = [[9, 3], [1, 3], [3, 3]].map(([col, row]) => crop(cliff, col!, row!));
const cliffWall = [crop(cliff, 9, 4)];
const cliffFoot = [[0, 5], [2, 5]].map(([col, row]) => crop(cliff, col!, row!));

const body = `/** Grass banks, dark-grass edges, and the south cliff. Generated by scripts/cut-shores.ts. -1 is the hole. */
function px(hex: string): Int32Array {
  const out = new Int32Array(256);
  for (let i = 0; i < 256; i += 1) {
    const h = hex.slice(i * 6, i * 6 + 6);
    out[i] = h === '000000' ? -1 : Number.parseInt(h, 16);
  }
  return out;
}

/** Light grass autotile, cols 0–11 × rows 0–3 of Tileset Grass Summer.png, laid over water. Index = row * 12 + col. */
export const SHORE_BANK: readonly Int32Array[] = [
${tiles.map((tile) => `  px('${hexOf(tile)}'),`).join('\n')}
];

/** Dark grass autotile, cols 12–23 × rows 0–3, laid over the light flat. Same index as SHORE_BANK. */
export const DARK_EDGE: readonly Int32Array[] = [
${darkEdges.map((tile) => `  px('${hexOf(tile)}'),`).join('\n')}
];

/** Tileset Grass Cliff Tileset Summer.png dirt face. Cap: straight (9,3), west end (1,3), east end (3,3). */
export const CLIFF_CAP_PX: readonly Int32Array[] = [
${cliffCap.map((tile) => `  px('${hexOf(tile)}'),`).join('\n')}
];
/** Wall (9,4). */
export const CLIFF_WALL_PX: readonly Int32Array[] = [
${cliffWall.map((tile) => `  px('${hexOf(tile)}'),`).join('\n')}
];
/** Waterline (0,5) and (2,5): two halves of one wave, alternated by column. */
export const CLIFF_FOOT_PX: readonly Int32Array[] = [
${cliffFoot.map((tile) => `  px('${hexOf(tile)}'),`).join('\n')}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.warn(`wrote ${tiles.length} banks, ${darkEdges.length} dark edges`);
