/**
 * Crop the first Tiny Farm slice into the runtime art folder.
 * Source sheets stay outside the repo. Re-run only when those sheets change.
 *
 *   npx vite-node scripts/cut-tiny-farm.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { createImage, readPng, stats, writePng, type Rgba } from './png';
import { CACHE, packRoot } from './pack-paths';

const PACK = packRoot();
const GRASS_SHEET = path.join(PACK, 'Tileset/Tileset Grass Summer.png');
const PINE_SHEET = path.join(PACK, 'Objects/Tree/Common/No Shadow/Pine Tree.png');
const TILES = path.join(CACHE, 'tiles');
const PROPS = path.join(CACHE, 'props');

/** Tile column, row on the 16px summer grass sheet. */
const GROUND: Record<string, readonly [number, number]> = {
  'grass-0': [9, 2],
  'grass-1': [21, 2],
  'path-center': [9, 10],
  'path-n': [10, 8],
  'path-e': [11, 10],
  'path-s': [9, 11],
  'path-w': [1, 9],
  'path-ne': [11, 8],
  'path-nw': [1, 8],
  'path-se': [11, 11],
  'path-sw': [8, 11],
  'path-ns': [2, 11],
  'path-ew': [0, 9],
  'path-end-s': [0, 8],
  'path-end-n': [0, 10],
  'path-end-e': [1, 11],
  'path-end-w': [3, 11],
  'path-island': [0, 11],
  'path-in-nw': [5, 9],
  'path-in-ne': [6, 9],
  'path-in-se': [6, 10],
  'path-in-sw': [5, 10],
};

const PINE = { x: 96, y: 2, w: 34, h: 45 };
/** Feet stay on the last row. The canopy meets the trunk 18px above that, the existing sort line. */
const TRUNK_SPLIT = 18;

function crop(sheet: Rgba, x: number, y: number, w: number, h: number): Rgba {
  const out = createImage(w, h);
  for (let yy = 0; yy < h; yy += 1) {
    const from = ((y + yy) * sheet.width + x) * 4;
    out.data.set(sheet.data.subarray(from, from + w * 4), yy * w * 4);
  }
  return out;
}

function rgbOf(img: Rgba): number[] {
  const colors: number[] = [];
  for (let i = 0; i < img.width * img.height; i += 1) {
    const o = i * 4;
    if (img.data[o + 3] === 0) throw new Error('ground tile has a transparent pixel');
    colors.push((img.data[o]! << 16) | (img.data[o + 1]! << 8) | img.data[o + 2]!);
  }
  return colors;
}

const grass = readPng(GRASS_SHEET);
if (grass.width !== 384 || grass.height !== 640) {
  throw new Error(`summer grass sheet is ${grass.width}×${grass.height}, expected 384×640`);
}

fs.mkdirSync(TILES, { recursive: true });
fs.mkdirSync(PROPS, { recursive: true });
const packed: Record<string, number[]> = {};
function flatten(img: Rgba, fill: number): Rgba {
  const out = createImage(img.width, img.height);
  for (let i = 0; i < img.width * img.height; i += 1) {
    const o = i * 4;
    const src = img.data[o + 3] === 0 ? fill : ((img.data[o]! << 16) | (img.data[o + 1]! << 8) | img.data[o + 2]!);
    out.data[o] = (src >>> 16) & 255;
    out.data[o + 1] = (src >>> 8) & 255;
    out.data[o + 2] = src & 255;
    out.data[o + 3] = 255;
  }
  return out;
}

for (const [name, [col, row]] of Object.entries(GROUND)) {
  const img = crop(grass, col * 16, row * 16, 16, 16);
  writePng(path.join(TILES, `${name}.png`), img);
  packed[name] = rgbOf(img);
  const s = stats(img);
  console.warn(`${name.padEnd(14)} ${col},${row} colors=${s.colors} loose=${s.loose}`);
}

const lightFill = packed['grass-0']![0]!;
const darkFill = packed['grass-1']![0]!;
const extras: Record<string, Rgba> = {
  'grass-ledge-0': flatten(crop(grass, 5 * 16, 24 * 16, 16, 16), lightFill),
  'grass-ledge-1': flatten(crop(grass, 17 * 16, 24 * 16, 16, 16), darkFill),
  'grass-speck-0': flatten(crop(grass, 5 * 16, 1 * 16, 16, 16), lightFill),
  'grass-speck-1': flatten(crop(grass, 17 * 16, 1 * 16, 16, 16), darkFill),
};
for (const [name, img] of Object.entries(extras)) {
  writePng(path.join(TILES, `${name}.png`), img);
  packed[name] = rgbOf(img);
  console.warn(`${name.padEnd(14)} colors=${stats(img).colors}`);
}

const pine = readPng(PINE_SHEET);
if (pine.width !== 256 || pine.height !== 96) {
  throw new Error(`pine sheet is ${pine.width}×${pine.height}, expected 256×96`);
}
const tree = crop(pine, PINE.x, PINE.y, PINE.w, PINE.h);
const trunk = crop(tree, 0, tree.height - TRUNK_SPLIT, tree.width, TRUNK_SPLIT);
const canopy = crop(tree, 0, 0, tree.width, tree.height - TRUNK_SPLIT);
writePng(path.join(PROPS, 'tree-trunk.png'), trunk);
writePng(path.join(PROPS, 'tree-canopy.png'), canopy);
for (const [name, img] of [['tree-trunk', trunk], ['tree-canopy', canopy]] as const) {
  const s = stats(img);
  const box = s.opaqueBox;
  console.warn(`${name} ${img.width}×${img.height} opaque=${box ? `${box.w}×${box.h} @${box.x},${box.y}` : '-'} colors=${s.colors} loose=${s.loose} alpha=${s.alphaClean}`);
}

const body = `/** Runtime pixels for the Tiny Farm ground crops. Generated by scripts/cut-tiny-farm.ts. */
function rgb(hex: string): Int32Array {
  const out = new Int32Array(hex.length / 6);
  for (let i = 0; i < out.length; i += 1) out[i] = Number.parseInt(hex.slice(i * 6, i * 6 + 6), 16);
  return out;
}

export const TILE_PX = {
${Object.entries(packed).map(([name, colors]) => `  '${name}': rgb('${colors.map((c) => c.toString(16).padStart(6, '0')).join('')}'),`).join('\n')}
} as const;

export type GroundTileName = keyof typeof TILE_PX;
`;
fs.writeFileSync(path.join(TILES, 'pixels.ts'), body);
console.warn('wrote', TILES);
