/**
 * Crop decorated spring grass into runtime pixels.
 * Source sheet stays in the gitignored pack. Holes are -1 so the flat grass shows through.
 *
 *   npx vite-node scripts/cut-tufts.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { readPng, type Rgba } from './png';
import { CACHE, packRoot } from './pack-paths';

const PACK = packRoot();
const OUT = path.join(CACHE, 'tiles/tufts.ts');
const TILE = 16;

function crop(sheet: Rgba, col: number, row: number): Int32Array | null {
  const px = new Int32Array(TILE * TILE);
  const colors = new Set<number>();
  let green = 0;
  let opaque = 0;
  for (let y = 0; y < TILE; y += 1) {
    for (let x = 0; x < TILE; x += 1) {
      const o = ((row * TILE + y) * sheet.width + col * TILE + x) * 4;
      const a = sheet.data[o + 3]!;
      const r = sheet.data[o]!;
      const g = sheet.data[o + 1]!;
      const b = sheet.data[o + 2]!;
      if (a < 200 || (r < 24 && g < 24 && b < 24)) {
        px[y * TILE + x] = -1;
        continue;
      }
      const color = (r << 16) | (g << 8) | b;
      px[y * TILE + x] = color;
      colors.add(color);
      opaque += 1;
      if (g > r + 8 && g > b) green += 1;
    }
  }
  if (opaque < 140 || opaque > 250) return null;
  if (colors.size < 4) return null;
  if (green < opaque * 0.55) return null;
  return px;
}

function hexOf(px: Int32Array): string {
  let s = '';
  for (let i = 0; i < px.length; i += 1) {
    const c = px[i]!;
    s += c < 0 ? '000000' : (c & 0xffffff).toString(16).padStart(6, '0');
  }
  return s;
}

const grass = readPng(path.join(PACK, 'Tileset/Tileset Grass Summer.png'));
const light: string[] = [];
const dark: string[] = [];
for (let row = 0; row <= 3; row += 1) {
  for (let col = 0; col <= 10; col += 1) {
    const tile = crop(grass, col, row);
    if (tile) light.push(hexOf(tile));
    const shade = crop(grass, col + 12, row);
    if (shade) dark.push(hexOf(shade));
  }
}

const body = `/** Decorated grass. Generated by scripts/cut-tufts.ts from Tileset Grass Summer.png rows 0–3. -1 is a hole. */
function px(hex: string): Int32Array {
  const out = new Int32Array(256);
  for (let i = 0; i < 256; i += 1) {
    const h = hex.slice(i * 6, i * 6 + 6);
    out[i] = h === '000000' ? -1 : Number.parseInt(h, 16);
  }
  return out;
}

export const GRASS_TUFT_LIGHT: readonly Int32Array[] = [
${light.map((hex) => `  px('${hex}'),`).join('\n')}
];

export const GRASS_TUFT_DARK: readonly Int32Array[] = [
${dark.map((hex) => `  px('${hex}'),`).join('\n')}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.warn(`light ${light.length} dark ${dark.length}`);
