/**
 * Cut scene B's ground decals into runtime pixels.
 * Source sheet stays in the gitignored pack. Re-run only when that sheet changes.
 *
 *   npx vite-node scripts/cut-decals.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { readPng, type Rgba } from './png';
import { CACHE, packRoot } from './pack-paths';

const PACK = packRoot();
const TILE = 16;
const OUT = path.join(CACHE, 'tiles/decals.ts');

function crop(sheet: Rgba, col: number, row: number): Int32Array {
  const px = new Int32Array(TILE * TILE);
  for (let y = 0; y < TILE; y += 1) {
    for (let x = 0; x < TILE; x += 1) {
      const o = ((row * TILE + y) * sheet.width + col * TILE + x) * 4;
      const hole = sheet.data[o + 3]! < 128;
      px[y * TILE + x] = hole ? -1 : (sheet.data[o]! << 16) | (sheet.data[o + 1]! << 8) | sheet.data[o + 2]!;
    }
  }
  return px;
}

function hexOf(px: Int32Array): string {
  let s = '';
  for (const c of px) s += c < 0 ? '------' : (c & 0xffffff).toString(16).padStart(6, '0');
  return s;
}

const sheet = readPng(path.join(PACK, 'Tileset/ALL props seasons.png'));
const LAWN = [[10, 1], [10, 0], [2, 1], [6, 1], [3, 0], [7, 0], [1, 0]] as const;
const PATH = [[0, 6], [1, 6], [2, 6], [5, 6], [6, 6]] as const;
const WATER = [[0, 7], [1, 7], [5, 7]] as const;
const list = (cells: readonly (readonly [number, number])[]) =>
  cells.map(([col, row]) => `  px('${hexOf(crop(sheet, col, row))}'),`).join('\n');

const body = `/** Ground decals from Tileset/ALL props seasons.png. Generated by scripts/cut-decals.ts. -1 is the hole. */
function px(hex: string): Int32Array {
  const out = new Int32Array(256);
  for (let i = 0; i < 256; i += 1) {
    const h = hex.slice(i * 6, i * 6 + 6);
    out[i] = h === '------' ? -1 : Number.parseInt(h, 16);
  }
  return out;
}

/** Rows 0–1: ground cover and the grass plant at (10,0)/(10,1). */
export const LAWN_DECALS: readonly Int32Array[] = [
${list(LAWN)}
];

/** Row 6: pebbles and dirt spots. */
export const PATH_DECALS: readonly Int32Array[] = [
${list(PATH)}
];

/** Row 7: dots on water. */
export const WATER_DECALS: readonly Int32Array[] = [
${list(WATER)}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.warn('wrote', OUT);
